Grade case insensitive
AY2425S1-CS2103T-T08-4/tp pull request #131
Opened 2024-11-05 04:50 UTC by dominopizzaaaa

Fixes #126

2024-11-05 06:33 UTC, juancarlovieri requested changes

2024-11-05 06:33 UTC, juancarlovieri commented on src/main/java/seedu/address/model/person/GradeList.java
> +        otherSortedGrades.sort(Comparator.comparing(Grade::getTestName));
simply comparing does not work. For example:

`[a, B]`
and
`[A,b]`

Instead, you can try to convert everything to lower case first before sorting and comparing.

2024-11-05 08:33 UTC, juancarlovieri submitted a review, later dismissed
lgtm good work wow

2024-11-05 10:12 UTC, dominopizzaaaa reviewed
lgtm (ig)

2024-11-06 00:50 UTC, izruff requested changes
`deleteGrade` cannot detect same test names with different cases, e.g. here `deleteGrade 1 n/test` works as expected (deletes 'Test') but `deleteGrade 1 n/Test` does not
![image](https://github.com/user-attachments/assets/10b738a0-ac4c-4529-80a1-ce6541b6fe03)

Otherwise, `addGrade` and `aggGrade` seems to be working fine.

The problem is `removeGrade` and `getGrade` do not normalize the test name before searching. And `deleteGradeCommand` internally calls `getGrade` to check for test name, hence the issue.

So the best fix I think is to make `getGrade` directly convert test name to lowercase.

```
    public Grade getGrade(String testName) {
        requireNonNull(testName);
        String normalizedTestName = testName.toLowerCase();
        return this.grades.get(normalizedTestName);
    }
```

2024-11-06 00:54 UTC, izruff commented on src/test/java/seedu/address/model/person/GradeListTest.java
> +        assertNull(gradeList.getGrade("tutorial"));
After modifying `getGrade` as mentioned, let's update the test cases to include variations of capital cases like "Midterm" and "MIDTERM".

2024-11-06 06:09 UTC, izruff approved these changes
Nice work!

2024-11-06 06:14 UTC, merged