Mark attendance command class
AY2425S1-CS2103T-T08-4/tp pull request #51
Opened 2024-10-16 15:55 UTC by Oceankoh

Closes #50

2024-10-16 16:28 UTC, Oceankoh commented
Close #52 as well

2024-10-16 16:50 UTC, Oceankoh commented
Closes #46 no longer an issue with the new data struct

2024-10-17 08:14 UTC, izruff commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +        }
Maybe also check for negative values?

2024-10-17 08:24 UTC, izruff commented on src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
> +        }
Same comment about negative values.

2024-10-17 08:28 UTC, izruff commented on src/main/java/seedu/address/model/person/AttendanceList.java
> +    public AttendanceList removeAttendance(LocalDateTime date) {
Add `requireNonNull(date)` here?

2024-10-17 08:33 UTC, izruff commented on src/test/java/seedu/address/model/person/AttendanceListTest.java
>      }
Should follow the new method name, `setAttendance`, instead of `addAttendance`.

2024-10-17 08:36 UTC, izruff commented on src/test/java/seedu/address/model/person/AttendanceTest.java
>          assertTrue(attendance.toString().equals("01/01/2024 12:00 Absent"));
You forgot to remove the date here :p

2024-10-17 08:37 UTC, izruff requested changes
Implementation is ok, just need some minor fixes and typos.

2024-10-17 14:36 UTC, izruff approved these changes
LGTM

2024-10-17 14:43 UTC, merged